version: '3.8'
services:
  db:
    image: ${DB_IMAGE}
    container_name: ${APP_NAME}-db
    networks:
      - backend
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:${DB_PORT}
networks:
  backend:
    name: lambda-local-network
